general.import = [
  "~/.config/alacritty/gruvbox_dark.toml"
]

    [window]
    opacity = 0.80 # Sets the background opacity to 90%

[cursor]
blink_interval = 500
[cursor.style]
shape = "Block"
blinking = "Always"




[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
# family = "MesloLGS Nerd Font Mono"
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "MesloLGS Nerd Font Mono"
family = "JetBrainsMono Nerd Font"
style = "Regular"

