# ~/.config/swaync/config.yml
notify:
  timeout: 5000    # 5 seconds
  font: JetBrainsMono Nerd Font 10
  position: top-right
  max_width: 400
  border: false
bar:
  enabled: false   # we donâ€™t need a second bar

